#!/bin/bash
# hyprland.sh — Launcher, screenshot stack, config generation

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

hyprland_setup() {
    [[ "$choiceDE" != "3" ]] && return

    _hyprland_choose_launcher
    _hyprland_install_launcher
    _hyprland_install_screenshot
    _hyprland_generate_conf
    sudo usermod -aG video "$USER"

    echo "Hyprland setup complete."
}

# ---------------------------------------------------------------------------
# Launcher
# ---------------------------------------------------------------------------

_hyprland_choose_launcher() {
    echo ""
    echo "Choose an application launcher for Hyprland:"
    echo "1) wofi         — lightweight, native wlroots launcher"
    echo "2) rofi-wayland — feature-rich, themeable  [default]"
    echo "3) walker       — modern, plugin-based (AUR)"
    read -p "Enter 1-3 [2]: " choiceLAUNCHER
    choiceLAUNCHER=${choiceLAUNCHER:-2}
    export choiceLAUNCHER
}

_hyprland_install_launcher() {
    # hyprland_launchers is 0-indexed: wofi=0  rofi-wayland=1  walker-bin=2
    # choiceLAUNCHER is 1-indexed, so subtract 1
    local pkg="${hyprland_launchers[$((choiceLAUNCHER - 1))]}"

    # walker-bin lives in the AUR; everything else is in the official repos
    if [[ "$choiceLAUNCHER" == "3" ]]; then
        install_yay "$pkg"
    else
        install_pacman "$pkg"
    fi
}

# ---------------------------------------------------------------------------
# Screenshot stack
# ---------------------------------------------------------------------------

_hyprland_install_screenshot() {
    echo "Installing screenshot stack..."
    install_yay "${hyprland_screenshot[@]}"
}

# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------

_hyprland_generate_conf() {
    mkdir -p ~/.config/hypr
    echo "Generating hyprland.conf..."

    local TERM_BIN
    case "${terminal_choice:-kitty}" in
        gnome-console) TERM_BIN="kgx"       ;;
        ptyxis)        TERM_BIN="ptyxis"    ;;
        konsole)       TERM_BIN="konsole"   ;;
        alacritty)     TERM_BIN="alacritty" ;;
        ghostty)       TERM_BIN="ghostty"   ;;
        kitty|*)       TERM_BIN="kitty"     ;;
    esac

    local MENU_CMD
    case ${choiceLAUNCHER:-2} in
        1) MENU_CMD="wofi --show drun" ;;
        3) MENU_CMD="walker"           ;;
        *) MENU_CMD="rofi -show drun"  ;;
    esac

    local CLIP_CMD
    case ${choiceLAUNCHER:-2} in
        1) CLIP_CMD="wofi --dmenu"   ;;
        3) CLIP_CMD="walker --dmenu" ;;
        *) CLIP_CMD="rofi -dmenu"    ;;
    esac

    cat > ~/.config/hypr/hyprland.conf << EOF
# =============================================================================
# Hyprland configuration — generated by archinstall
# Full reference: https://wiki.hyprland.org/Configuring/
# =============================================================================

# --- Monitors ----------------------------------------------------------------
monitor=,preferred,auto,1

# --- Autostart ---------------------------------------------------------------
exec-once = hyprpolkitagent
exec-once = nm-applet
exec-once = swaync
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# --- Environment variables ---------------------------------------------------
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Adwaita
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# --- Look & feel -------------------------------------------------------------
general {
    gaps_in             = 5
    gaps_out            = 10
    border_size         = 2
    col.active_border   = rgba(88c0d0ff) rgba(81a1c1ff) 45deg
    col.inactive_border = rgba(4c566aaa)
    layout              = dwindle
    resize_on_border    = true
}

decoration {
    rounding = 10
    blur {
        enabled           = true
        size              = 6
        passes            = 3
        new_optimizations = true
    }
    shadow {
        enabled      = true
        range        = 10
        render_power = 2
        color        = rgba(1a1a1aee)
    }
}

animations {
    enabled = true
    bezier  = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows,    1, 7,  myBezier
    animation = windowsOut, 1, 7,  default, popin 80%
    animation = border,     1, 10, default
    animation = fade,       1, 7,  default
    animation = workspaces, 1, 6,  default
}

# --- Layouts -----------------------------------------------------------------
dwindle {
    pseudotile     = true
    preserve_split = true
}

master {
    new_status = master
}

# --- Input -------------------------------------------------------------------
input {
    kb_layout    = us
    follow_mouse = 1
    sensitivity  = 0
    touchpad {
        natural_scroll = false
        tap-to-click   = true
        drag_lock      = false
    }
}

gestures {
    workspace_swipe = true
}

# --- Misc --------------------------------------------------------------------
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo   = true
}

# =============================================================================
# Keybindings  (SUPER = Windows key)
# =============================================================================
\$mainMod     = SUPER
\$terminal    = ${TERM_BIN}
\$fileManager = nautilus
\$menu        = ${MENU_CMD}

# Applications
bind = \$mainMod,       Return, exec, \$terminal
bind = \$mainMod,       E,      exec, \$fileManager
bind = \$mainMod,       R,      exec, \$menu
bind = \$mainMod,       B,      exec, xdg-open https://

# Window management
bind = \$mainMod,       Q,      killactive
bind = \$mainMod,       F,      fullscreen, 0
bind = \$mainMod SHIFT, F,      fullscreen, 1
bind = \$mainMod,       V,      togglefloating
bind = \$mainMod,       P,      pseudo
bind = \$mainMod,       J,      togglesplit

# Focus
bind = \$mainMod, left,  movefocus, l
bind = \$mainMod, right, movefocus, r
bind = \$mainMod, up,    movefocus, u
bind = \$mainMod, down,  movefocus, d

# Move windows
bind = \$mainMod SHIFT, left,  movewindow, l
bind = \$mainMod SHIFT, right, movewindow, r
bind = \$mainMod SHIFT, up,    movewindow, u
bind = \$mainMod SHIFT, down,  movewindow, d

# Resize windows
binde = \$mainMod CTRL, left,  resizeactive, -20 0
binde = \$mainMod CTRL, right, resizeactive,  20 0
binde = \$mainMod CTRL, up,    resizeactive,  0 -20
binde = \$mainMod CTRL, down,  resizeactive,  0  20

# Workspaces 1-9
\$(for i in \$(seq 1 9); do
    echo "bind = \\\$mainMod,       \$i, workspace,       \$i"
    echo "bind = \\\$mainMod SHIFT, \$i, movetoworkspace, \$i"
done)

# Special workspace (scratchpad)
bind = \$mainMod,       S, togglespecialworkspace, magic
bind = \$mainMod SHIFT, S, movetoworkspace,        special:magic

# Scroll through workspaces with mouse
bind = \$mainMod, mouse_down, workspace, e+1
bind = \$mainMod, mouse_up,   workspace, e-1

# Move/resize with mouse
bindm = \$mainMod, mouse:272, movewindow
bindm = \$mainMod, mouse:273, resizewindow

# Screenshots (grimblast)
bind = ,                Print, exec, grimblast copy output
bind = \$mainMod,       Print, exec, grimblast copy area
bind = \$mainMod SHIFT, Print, exec, grimblast copy active

# Clipboard history
bind = \$mainMod, C, exec, cliphist list | ${CLIP_CMD} | cliphist decode | wl-copy

# Colour picker
bind = \$mainMod SHIFT, C, exec, hyprpicker -a

# Notifications
bind = \$mainMod,       N, exec, swaync-client -t
bind = \$mainMod SHIFT, N, exec, swaync-client -C

# Lock screen
bind = \$mainMod, L, exec, hyprlock

# Audio (wireplumber + playerctl)
bindel = , XF86AudioRaiseVolume,  exec, wpctl set-volume    @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume,  exec, wpctl set-volume    @DEFAULT_AUDIO_SINK@ 5%-
bindl  = , XF86AudioMute,         exec, wpctl set-mute      @DEFAULT_AUDIO_SINK@ toggle
bindl  = , XF86AudioMicMute,      exec, wpctl set-mute      @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = , XF86AudioPlay,         exec, playerctl play-pause
bindl  = , XF86AudioPrev,         exec, playerctl previous
bindl  = , XF86AudioNext,         exec, playerctl next

# Brightness (brightnessctl)
bindel = , XF86MonBrightnessUp,   exec, brightnessctl set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

# =============================================================================
# Window rules
# =============================================================================
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin,   title:^(Picture-in-Picture)$
EOF

    echo "hyprland.conf written to ~/.config/hypr/hyprland.conf"
}
