#!/bin/bash
# shell.sh — Shell selection, Starship, per-shell configs, shared aliases & functions

# ---------------------------------------------------------------------------
# Shell setup (bash / zsh / fish)
# ---------------------------------------------------------------------------

shell_setup() {
    if [[ "$mode" == "1" ]]; then
        echo "Choose your shell:"
        echo "1) Bash (keep current)"
        echo "2) Zsh"
        echo "3) Fish"
        read -p "Enter 1-3: " choiceSHELL
    fi

    case $choiceSHELL in
        2)
            install_pacman zsh
            chsh -s "$(which zsh)" "$USER"
            echo "Zsh installed and set as default shell."
            ;;
        3)
            install_pacman fish
            chsh -s "$(which fish)" "$USER"
            echo "Fish installed and set as default shell."
            ;;
        *)
            echo "Keeping Bash."
            ;;
    esac

    if [[ "$mode" == "1" ]]; then
        echo "Apply shell customizations? (Starship prompt, aliases, functions)"
        echo "1) Yes  2) No"
        read -p "Enter 1-2: " choiceSS
    fi

    [[ "$choiceSS" != "1" ]] && return

    curl -sS https://starship.rs/install.sh | sh -s -- --yes

    case $choiceSHELL in
        1) _apply_bash_config  ;;
        2) _apply_zsh_config   ;;
        3) _apply_fish_config  ;;
    esac

    echo "Shell setup done."
}

_apply_bash_config() {
    if [[ "$choiceTPKG" == "1" ]]; then
        cp .betterbash ~/.bashrc
    else
        cp .bashrc ~/.bashrc
    fi

    if [[ "$terminal_choice" == "ghostty" || "$terminal_choice" == "kitty" ]]; then
        mkdir -p ~/.config/fastfetch
        cp -r fastfetch ~/.config/
    fi
}

_apply_zsh_config() {
    install_pacman zsh-autosuggestions zsh-syntax-highlighting zsh-completions

    local ZSHRC="$HOME/.zshrc"

    cat > "$ZSHRC" << 'EOF'
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

eval "$(starship init zsh)"
EOF

    if command -v zoxide &>/dev/null; then
        echo 'eval "$(zoxide init zsh)"' >> "$ZSHRC"
    fi

    cat >> "$ZSHRC" << 'EOF'

# Plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fpath=(/usr/share/zsh/site-functions $fpath)
autoload -Uz compinit && compinit

EOF

    if [[ "$terminal_choice" == "ghostty" || "$terminal_choice" == "kitty" ]]; then
        mkdir -p ~/.config/fastfetch
        cp -r fastfetch ~/.config/
        echo "fastfetch" >> "$ZSHRC"
    fi

    if [[ "$choiceTPKG" == "1" ]]; then
        cat >> "$ZSHRC" << 'EOF'
# Completion for eza, rg, fd
[ -f /usr/share/zsh/site-functions/_eza ] && source /usr/share/zsh/site-functions/_eza

# Yazi wrapper — cd on exit
function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

export EDITOR='micro'

# Aliases
alias ls='eza --icons'
alias grep='rg'
alias find='fd'
alias cd='z'
alias cat='bat'
EOF
    else
        cat >> "$ZSHRC" << 'EOF'
# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
EOF
    fi

    _append_common_aliases "$ZSHRC"
    _append_common_functions "$ZSHRC"
}

_apply_fish_config() {
    install_pacman fisher 2>/dev/null || true

    local FISH_DIR="$HOME/.config/fish"
    mkdir -p "$FISH_DIR/functions"

    cat > "$FISH_DIR/config.fish" << 'EOF'
# Fish config — generated by archinstall

if status is-interactive
    starship init fish | source
EOF

    if command -v zoxide &>/dev/null; then
        echo "    zoxide init fish | source" >> "$FISH_DIR/config.fish"
    fi

    if [[ "$terminal_choice" == "ghostty" || "$terminal_choice" == "kitty" ]]; then
        mkdir -p ~/.config/fastfetch
        cp -r fastfetch ~/.config/
        echo "    fastfetch" >> "$FISH_DIR/config.fish"
    fi

    cat >> "$FISH_DIR/config.fish" << 'EOF'
end
EOF

    if [[ "$choiceTPKG" == "1" ]]; then
        cat >> "$FISH_DIR/config.fish" << 'EOF'

# Aliases
alias ls 'eza --icons'
alias grep 'rg'
alias find 'fd'
alias cat 'bat'
EOF
        cat > "$FISH_DIR/functions/y.fish" << 'EOF'
function y
    set tmp (mktemp -t "yazi-cwd.XXXXXX")
    yazi $argv --cwd-file="$tmp"
    set cwd (cat -- "$tmp")
    if test -n "$cwd" -a "$cwd" != "$PWD"
        cd "$cwd"
    end
    rm -f -- "$tmp"
end
EOF
    else
        echo "alias ls 'ls --color=auto'" >> "$FISH_DIR/config.fish"
    fi

    cat >> "$FISH_DIR/config.fish" << 'EOF'

# Common aliases
alias update-system 'yay -Syyu --noconfirm && flatpak update -y --noninteractive'
alias clear-packages 'set orphans (yay -Qtdq); if test -n "$orphans"; yay -Rns --noconfirm $orphans; else; echo "No packages to clear."; end && flatpak remove --unused -y --noninteractive'
alias speedup-mirrors 'sudo reflector --sort rate --latest 20 --protocol https --save /etc/pacman.d/mirrorlist'
alias test-nvidia 'prime-run glxinfo | grep "OpenGL renderer"'
alias show-ip 'ip -4 addr show | grep inet | awk \'{print $2}\' | cut -d\'/\' -f1'
alias clear-cache 'sudo pacman -Scc --noconfirm && yay -Sc --noconfirm'
alias gs 'git status'
alias ga 'git add .'
alias gc 'git commit -m'
alias duh 'du -h --max-depth=1 | sort -hr'

# Functions
function mkcd
    if test -z "$argv[1]"
        echo "Usage: mkcd <directory>"
        return 1
    end
    mkdir -p "$argv[1]" && cd "$argv[1]" && echo "Created and entered: "(pwd)
end

function gitall
    if test -z "$argv[1]"
        echo "Usage: gitall \"commit message\""
        return 1
    end
    git add . && git commit -m "$argv[1]" && git push && echo "Changes committed and pushed."
end
EOF

    echo "Fish config written to $FISH_DIR/config.fish"
}

# ---------------------------------------------------------------------------
# Shared aliases & functions — appended to bash/zsh configs
# ---------------------------------------------------------------------------

_append_common_aliases() {
    local rc="$1"
    cat >> "$rc" << 'EOF'

alias update-system="yay -Syyu --noconfirm && flatpak update -y --noninteractive"
alias clear-packages='orphans=$(yay -Qtdq); if [ -n "$orphans" ]; then yay -Rns --noconfirm $orphans; else echo "No packages to clear."; fi && flatpak remove --unused -y --noninteractive'
alias speedup-mirrors="sudo reflector --sort rate --latest 20 --protocol https --save /etc/pacman.d/mirrorlist"
alias test-nvidia="prime-run glxinfo | grep 'OpenGL renderer'"
alias show-ip="ip -4 addr show | grep inet | awk '{print \$2}' | cut -d'/' -f1"
alias show-ip-wifi="ip -4 addr show | grep inet | grep -E 'wlan|wlp' | awk '{print \$2}' | cut -d'/' -f1"
alias clear-cache="sudo pacman -Scc --noconfirm && yay -Sc --noconfirm"
alias gs='git status'
alias ga='git add .'
alias gc='git commit -m'
alias duh='du -h --max-depth=1 | sort -hr'
EOF
}

_append_common_functions() {
    local rc="$1"
    cat >> "$rc" << 'EOF'

extract() {
    local delete="n" confirm="y"
    while [ "$1" = "--delete" ] || [ "$1" = "--noconfirm" ]; do
        [ "$1" = "--delete" ] && delete="y"
        [ "$1" = "--no-confirm" ] && confirm="n"
        shift
    done
    for f in *.{zip,rar,7z,tar.gz,tar,tgz,tar.bz2}; do
        [ -f "$f" ] || continue
        case "$f" in
            *.zip)          unzip "$f"    ;;
            *.rar)          unrar x "$f"  ;;
            *.7z)           7z x "$f"     ;;
            *.tar.gz|*.tgz) tar -xzf "$f" ;;
            *.tar)          tar -xf "$f"  ;;
            *.tar.bz2)      tar -xjf "$f" ;;
        esac || { echo "Failed to extract $f"; return 1; }
        if [ "$delete" = "y" ]; then
            [ "$confirm" = "y" ] && read -p "Delete $f? [y/N] " c && [ "$c" = "y" ] && rm -f "$f"
            [ "$confirm" = "n" ] && rm -f "$f"
        fi
    done
}

mkcd() {
    [ -z "$1" ] && { echo "Usage: mkcd <directory>"; return 1; }
    mkdir -p "$1" && cd "$1" && echo "Created and entered: $(pwd)"
}

gitall() {
    [ -z "$1" ] && { echo "Usage: gitall \"commit message\""; return 1; }
    git add . && git commit -m "$1" && git push && echo "Changes committed and pushed."
}
EOF
}
